# Configuracion del API Gateway con NGINX
events { worker_connections 1024; }

http {
    upstream producto_service {
        # Si usas Docker, usamos el nombre del contenedor
        server producto-service:8081;
    }

    server {
        listen 8080; # Puerto de entrada para el usuario
        server_name localhost;

        location /productos {
            proxy_pass http://producto_service/productos;
        }

        # Swagger UI a través del Gateway
        location /q/swagger-ui/ {
            proxy_pass http://producto_service/q/swagger-ui/;
        }
    }
}